#!/usr/bin/env python3
import os
import sys
import serial
from time import sleep
ARDUBOY_LOCATION = "/dev/cu.usbmodem141201"

# Check if the file_name was specified
if len(sys.argv) != 1:
  file_name = sys.argv[1]
else:
  print("File name not provided")
  exit()

# Check if the arduboy is here
try:
  arduboy = serial.Serial(ARDUBOY_LOCATION)
except Exception:
  print("Plug the Arduboy in and turn it on")
  exit()

# Opening a serial port at 1200 baud and closing it puts Arduino Leonardo into bootloader mode
arduboy = serial.Serial(ARDUBOY_LOCATION, 1200)
arduboy.close()
sleep(1) # Wait for the Arduboy to go into bootloader mode

# This command is from MY Arduino IDE so YOU may have to change this command
os.system(f"/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avrdude -C/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf -v -patmega32u4 -cavr109 -P{ARDUBOY_LOCATION} -b57600 -D -Uflash:w:{file_name}:i")
print("Uploader done. Thank you.")
